# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        	pretty
relative_permalinks: true

# Setup
title:            Ciar&#225;n Sch&#252;tte
tagline:          ''
description:      'stdout'
url:              http://ciaranschutte.com
baseurl:          /





