# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ciaran Schutte
tagline:          ''
description:      'My stdout'
url:              http://ciaranschutte.com
baseurl:          /



paginate:         5


